### ISSUE TITLE
Tab for react-syntax-highlighter?

### ISSUE THREAD

**Issue by karlhorky** [SaraVieira/prism-theme-converter#1]
Hey @SaraVieira ! 👋 Thanks for the awesome project.

Would you be up for having a tab that converts to the [`react-syntax-highlighter`](https://github.com/react-syntax-highlighter/react-syntax-highlighter) theme format? (see example here: https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/styles/prism/synthwave84.js)

The format seems fairly simple, but if there are any complexities, there is a script for converting from Prism.js themes that may shed light:

https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/scripts/build-stylesheets-refractor.js

If you would rather someone else take this over, you could also point me in the right direction and I can probably take a look soon!

**Comment by SaraVieira** [comment]
Hey!

The code was a mess, I touched it up a bit to make more sense and I also added that

Hope it's useful :)

**Comment by karlhorky** [comment]
wowowow awesome and fast, thanks! good job! 🚀 🙌

**Comment by SaraVieira** [comment]
You are very welcome :D

**Comment by karlhorky** [comment]
lol my PR in that project escalated quickly 😅 I guess maybe the format / script is going to change! 

May want to keep an eye on this PR:

https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/305

**Comment by SaraVieira** [comment]
Thank you for letting me know!

I subscribed to it 👍
